---
- name: Install Apache Web Server
  hosts: all
  become: yes
  tasks:

    - name: update repository index 
      apt:
        update_cache: yes
 
    - name: Install Apache dex
      apt:
        name: apache2
        state: present

    - name: add PHP support for apache
      apt:
        name: libapache2-mod-php
